/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApresPriereRouteImport } from './routes/apres-priere'
import { Route as CoucherRouteImport } from './routes/coucher'
import { Route as EcouteRouteImport } from './routes/ecoute'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as FavorisLectureRouteImport } from './routes/favoris-lecture'
import { Route as HorairesRouteImport } from './routes/horaires'
import { Route as InstallRouteImport } from './routes/install'
import { Route as KhatmaRouteImport } from './routes/khatma'
import { Route as MatinRouteImport } from './routes/matin'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RappelsRouteImport } from './routes/rappels'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ReveilRouteImport } from './routes/reveil'
import { Route as SoirRouteImport } from './routes/soir'
import { Route as SortieRouteImport } from './routes/sortie'
import { Route as TadabburRouteImport } from './routes/tadabbur'
import { Route as VoyageRouteImport } from './routes/voyage'
import { Route as WirdRouteImport } from './routes/wird'
import { Route as ApiChallengesRouteImport } from './routes/api.challenges'
import { Route as ChallengeIdRouteImport } from './routes/challenge.$id'
import { Route as CompteurIndexRouteImport } from './routes/compteur.index'
import { Route as CompteurDhikrIdRouteImport } from './routes/compteur.$dhikrId'
import { Route as DefisIndexRouteImport } from './routes/defis.index'
import { Route as DefisNouveauRouteImport } from './routes/defis.nouveau'
import { Route as ParametresApparenceRouteImport } from './routes/parametres.apparence'
import { Route as SourateSurahRouteImport } from './routes/sourate.$surah'
import { Route as ApiChallengesIdRouteImport } from './routes/api.challenges.$id'
import { Route as EtudeSurahAyahRouteImport } from './routes/etude.$surah.$ayah'
import { Route as QuranLireSurahRouteImport } from './routes/quran.lire.$surah'
import { Route as QuranPagePageRouteImport } from './routes/quran.page.$page'
import { Route as ApiChallengesIdJoinRouteImport } from './routes/api.challenges.$id.join'
import { Route as ApiChallengesIdProgressRouteImport } from './routes/api.challenges.$id.progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresPriereRoute = ApresPriereRouteImport.update({
  id: '/apres-priere',
  path: '/apres-priere',
  getParentRoute: () => rootRouteImport,
} as any)
const CoucherRoute = CoucherRouteImport.update({
  id: '/coucher',
  path: '/coucher',
  getParentRoute: () => rootRouteImport,
} as any)
const EcouteRoute = EcouteRouteImport.update({
  id: '/ecoute',
  path: '/ecoute',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisLectureRoute = FavorisLectureRouteImport.update({
  id: '/favoris-lecture',
  path: '/favoris-lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const HorairesRoute = HorairesRouteImport.update({
  id: '/horaires',
  path: '/horaires',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const KhatmaRoute = KhatmaRouteImport.update({
  id: '/khatma',
  path: '/khatma',
  getParentRoute: () => rootRouteImport,
} as any)
const MatinRoute = MatinRouteImport.update({
  id: '/matin',
  path: '/matin',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RappelsRoute = RappelsRouteImport.update({
  id: '/rappels',
  path: '/rappels',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ReveilRoute = ReveilRouteImport.update({
  id: '/reveil',
  path: '/reveil',
  getParentRoute: () => rootRouteImport,
} as any)
const SoirRoute = SoirRouteImport.update({
  id: '/soir',
  path: '/soir',
  getParentRoute: () => rootRouteImport,
} as any)
const SortieRoute = SortieRouteImport.update({
  id: '/sortie',
  path: '/sortie',
  getParentRoute: () => rootRouteImport,
} as any)
const TadabburRoute = TadabburRouteImport.update({
  id: '/tadabbur',
  path: '/tadabbur',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageRoute = VoyageRouteImport.update({
  id: '/voyage',
  path: '/voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const WirdRoute = WirdRouteImport.update({
  id: '/wird',
  path: '/wird',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesRoute = ApiChallengesRouteImport.update({
  id: '/api/challenges',
  path: '/api/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIdRoute = ChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteurIndexRoute = CompteurIndexRouteImport.update({
  id: '/compteur/',
  path: '/compteur/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteurDhikrIdRoute = CompteurDhikrIdRouteImport.update({
  id: '/compteur/$dhikrId',
  path: '/compteur/$dhikrId',
  getParentRoute: () => rootRouteImport,
} as any)
const DefisIndexRoute = DefisIndexRouteImport.update({
  id: '/defis/',
  path: '/defis/',
  getParentRoute: () => rootRouteImport,
} as any)
const DefisNouveauRoute = DefisNouveauRouteImport.update({
  id: '/defis/nouveau',
  path: '/defis/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresApparenceRoute = ParametresApparenceRouteImport.update({
  id: '/apparence',
  path: '/apparence',
  getParentRoute: () => ParametresRoute,
} as any)
const SourateSurahRoute = SourateSurahRouteImport.update({
  id: '/sourate/$surah',
  path: '/sourate/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesIdRoute = ApiChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChallengesRoute,
} as any)
const EtudeSurahAyahRoute = EtudeSurahAyahRouteImport.update({
  id: '/etude/$surah/$ayah',
  path: '/etude/$surah/$ayah',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranLireSurahRoute = QuranLireSurahRouteImport.update({
  id: '/quran/lire/$surah',
  path: '/quran/lire/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranPagePageRoute = QuranPagePageRouteImport.update({
  id: '/quran/page/$page',
  path: '/quran/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesIdJoinRoute = ApiChallengesIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ApiChallengesIdRoute,
} as any)
const ApiChallengesIdProgressRoute = ApiChallengesIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ApiChallengesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apres-priere': typeof ApresPriereRoute
  '/coucher': typeof CoucherRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/horaires': typeof HorairesRoute
  '/install': typeof InstallRoute
  '/khatma': typeof KhatmaRoute
  '/matin': typeof MatinRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/rappels': typeof RappelsRoute
  '/recherche': typeof RechercheRoute
  '/reveil': typeof ReveilRoute
  '/soir': typeof SoirRoute
  '/sortie': typeof SortieRoute
  '/tadabbur': typeof TadabburRoute
  '/voyage': typeof VoyageRoute
  '/wird': typeof WirdRoute
  '/api/challenges': typeof ApiChallengesRouteWithChildren
  '/challenge/$id': typeof ChallengeIdRoute
  '/compteur/$dhikrId': typeof CompteurDhikrIdRoute
  '/defis/nouveau': typeof DefisNouveauRoute
  '/parametres/apparence': typeof ParametresApparenceRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/compteur/': typeof CompteurIndexRoute
  '/defis/': typeof DefisIndexRoute
  '/api/challenges/$id': typeof ApiChallengesIdRouteWithChildren
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/lire/$surah': typeof QuranLireSurahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/api/challenges/$id/join': typeof ApiChallengesIdJoinRoute
  '/api/challenges/$id/progress': typeof ApiChallengesIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apres-priere': typeof ApresPriereRoute
  '/coucher': typeof CoucherRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/horaires': typeof HorairesRoute
  '/install': typeof InstallRoute
  '/khatma': typeof KhatmaRoute
  '/matin': typeof MatinRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/rappels': typeof RappelsRoute
  '/recherche': typeof RechercheRoute
  '/reveil': typeof ReveilRoute
  '/soir': typeof SoirRoute
  '/sortie': typeof SortieRoute
  '/tadabbur': typeof TadabburRoute
  '/voyage': typeof VoyageRoute
  '/wird': typeof WirdRoute
  '/api/challenges': typeof ApiChallengesRouteWithChildren
  '/challenge/$id': typeof ChallengeIdRoute
  '/compteur/$dhikrId': typeof CompteurDhikrIdRoute
  '/defis/nouveau': typeof DefisNouveauRoute
  '/parametres/apparence': typeof ParametresApparenceRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/compteur': typeof CompteurIndexRoute
  '/defis': typeof DefisIndexRoute
  '/api/challenges/$id': typeof ApiChallengesIdRouteWithChildren
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/lire/$surah': typeof QuranLireSurahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/api/challenges/$id/join': typeof ApiChallengesIdJoinRoute
  '/api/challenges/$id/progress': typeof ApiChallengesIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apres-priere': typeof ApresPriereRoute
  '/coucher': typeof CoucherRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/horaires': typeof HorairesRoute
  '/install': typeof InstallRoute
  '/khatma': typeof KhatmaRoute
  '/matin': typeof MatinRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/rappels': typeof RappelsRoute
  '/recherche': typeof RechercheRoute
  '/reveil': typeof ReveilRoute
  '/soir': typeof SoirRoute
  '/sortie': typeof SortieRoute
  '/tadabbur': typeof TadabburRoute
  '/voyage': typeof VoyageRoute
  '/wird': typeof WirdRoute
  '/api/challenges': typeof ApiChallengesRouteWithChildren
  '/challenge/$id': typeof ChallengeIdRoute
  '/compteur/$dhikrId': typeof CompteurDhikrIdRoute
  '/defis/nouveau': typeof DefisNouveauRoute
  '/parametres/apparence': typeof ParametresApparenceRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/compteur/': typeof CompteurIndexRoute
  '/defis/': typeof DefisIndexRoute
  '/api/challenges/$id': typeof ApiChallengesIdRouteWithChildren
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/lire/$surah': typeof QuranLireSurahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
  '/api/challenges/$id/join': typeof ApiChallengesIdJoinRoute
  '/api/challenges/$id/progress': typeof ApiChallengesIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apres-priere'
    | '/coucher'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/horaires'
    | '/install'
    | '/khatma'
    | '/matin'
    | '/parametres'
    | '/rappels'
    | '/recherche'
    | '/reveil'
    | '/soir'
    | '/sortie'
    | '/tadabbur'
    | '/voyage'
    | '/wird'
    | '/api/challenges'
    | '/challenge/$id'
    | '/compteur/$dhikrId'
    | '/defis/nouveau'
    | '/parametres/apparence'
    | '/sourate/$surah'
    | '/compteur/'
    | '/defis/'
    | '/api/challenges/$id'
    | '/etude/$surah/$ayah'
    | '/quran/lire/$surah'
    | '/quran/page/$page'
    | '/api/challenges/$id/join'
    | '/api/challenges/$id/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apres-priere'
    | '/coucher'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/horaires'
    | '/install'
    | '/khatma'
    | '/matin'
    | '/parametres'
    | '/rappels'
    | '/recherche'
    | '/reveil'
    | '/soir'
    | '/sortie'
    | '/tadabbur'
    | '/voyage'
    | '/wird'
    | '/api/challenges'
    | '/challenge/$id'
    | '/compteur/$dhikrId'
    | '/defis/nouveau'
    | '/parametres/apparence'
    | '/sourate/$surah'
    | '/compteur'
    | '/defis'
    | '/api/challenges/$id'
    | '/etude/$surah/$ayah'
    | '/quran/lire/$surah'
    | '/quran/page/$page'
    | '/api/challenges/$id/join'
    | '/api/challenges/$id/progress'
  id:
    | '__root__'
    | '/'
    | '/apres-priere'
    | '/coucher'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/horaires'
    | '/install'
    | '/khatma'
    | '/matin'
    | '/parametres'
    | '/rappels'
    | '/recherche'
    | '/reveil'
    | '/soir'
    | '/sortie'
    | '/tadabbur'
    | '/voyage'
    | '/wird'
    | '/api/challenges'
    | '/challenge/$id'
    | '/compteur/$dhikrId'
    | '/defis/nouveau'
    | '/parametres/apparence'
    | '/sourate/$surah'
    | '/compteur/'
    | '/defis/'
    | '/api/challenges/$id'
    | '/etude/$surah/$ayah'
    | '/quran/lire/$surah'
    | '/quran/page/$page'
    | '/api/challenges/$id/join'
    | '/api/challenges/$id/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresPriereRoute: typeof ApresPriereRoute
  CoucherRoute: typeof CoucherRoute
  EcouteRoute: typeof EcouteRoute
  FavorisRoute: typeof FavorisRoute
  FavorisLectureRoute: typeof FavorisLectureRoute
  HorairesRoute: typeof HorairesRoute
  InstallRoute: typeof InstallRoute
  KhatmaRoute: typeof KhatmaRoute
  MatinRoute: typeof MatinRoute
  ParametresRoute: typeof ParametresRouteWithChildren
  RappelsRoute: typeof RappelsRoute
  RechercheRoute: typeof RechercheRoute
  ReveilRoute: typeof ReveilRoute
  SoirRoute: typeof SoirRoute
  SortieRoute: typeof SortieRoute
  TadabburRoute: typeof TadabburRoute
  VoyageRoute: typeof VoyageRoute
  WirdRoute: typeof WirdRoute
  ApiChallengesRoute: typeof ApiChallengesRouteWithChildren
  ChallengeIdRoute: typeof ChallengeIdRoute
  CompteurDhikrIdRoute: typeof CompteurDhikrIdRoute
  DefisNouveauRoute: typeof DefisNouveauRoute
  SourateSurahRoute: typeof SourateSurahRoute
  CompteurIndexRoute: typeof CompteurIndexRoute
  DefisIndexRoute: typeof DefisIndexRoute
  EtudeSurahAyahRoute: typeof EtudeSurahAyahRoute
  QuranLireSurahRoute: typeof QuranLireSurahRoute
  QuranPagePageRoute: typeof QuranPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apres-priere': {
      id: '/apres-priere'
      path: '/apres-priere'
      fullPath: '/apres-priere'
      preLoaderRoute: typeof ApresPriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coucher': {
      id: '/coucher'
      path: '/coucher'
      fullPath: '/coucher'
      preLoaderRoute: typeof CoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoute': {
      id: '/ecoute'
      path: '/ecoute'
      fullPath: '/ecoute'
      preLoaderRoute: typeof EcouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris-lecture': {
      id: '/favoris-lecture'
      path: '/favoris-lecture'
      fullPath: '/favoris-lecture'
      preLoaderRoute: typeof FavorisLectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horaires': {
      id: '/horaires'
      path: '/horaires'
      fullPath: '/horaires'
      preLoaderRoute: typeof HorairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khatma': {
      id: '/khatma'
      path: '/khatma'
      fullPath: '/khatma'
      preLoaderRoute: typeof KhatmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matin': {
      id: '/matin'
      path: '/matin'
      fullPath: '/matin'
      preLoaderRoute: typeof MatinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rappels': {
      id: '/rappels'
      path: '/rappels'
      fullPath: '/rappels'
      preLoaderRoute: typeof RappelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveil': {
      id: '/reveil'
      path: '/reveil'
      fullPath: '/reveil'
      preLoaderRoute: typeof ReveilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soir': {
      id: '/soir'
      path: '/soir'
      fullPath: '/soir'
      preLoaderRoute: typeof SoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortie': {
      id: '/sortie'
      path: '/sortie'
      fullPath: '/sortie'
      preLoaderRoute: typeof SortieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tadabbur': {
      id: '/tadabbur'
      path: '/tadabbur'
      fullPath: '/tadabbur'
      preLoaderRoute: typeof TadabburRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage': {
      id: '/voyage'
      path: '/voyage'
      fullPath: '/voyage'
      preLoaderRoute: typeof VoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wird': {
      id: '/wird'
      path: '/wird'
      fullPath: '/wird'
      preLoaderRoute: typeof WirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges': {
      id: '/api/challenges'
      path: '/api/challenges'
      fullPath: '/api/challenges'
      preLoaderRoute: typeof ApiChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$id': {
      id: '/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof ChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compteur/': {
      id: '/compteur/'
      path: '/compteur'
      fullPath: '/compteur/'
      preLoaderRoute: typeof CompteurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compteur/$dhikrId': {
      id: '/compteur/$dhikrId'
      path: '/compteur/$dhikrId'
      fullPath: '/compteur/$dhikrId'
      preLoaderRoute: typeof CompteurDhikrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defis/': {
      id: '/defis/'
      path: '/defis'
      fullPath: '/defis/'
      preLoaderRoute: typeof DefisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defis/nouveau': {
      id: '/defis/nouveau'
      path: '/defis/nouveau'
      fullPath: '/defis/nouveau'
      preLoaderRoute: typeof DefisNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/apparence': {
      id: '/parametres/apparence'
      path: '/apparence'
      fullPath: '/parametres/apparence'
      preLoaderRoute: typeof ParametresApparenceRouteImport
      parentRoute: typeof ParametresRoute
    }
    '/sourate/$surah': {
      id: '/sourate/$surah'
      path: '/sourate/$surah'
      fullPath: '/sourate/$surah'
      preLoaderRoute: typeof SourateSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/$id': {
      id: '/api/challenges/$id'
      path: '/$id'
      fullPath: '/api/challenges/$id'
      preLoaderRoute: typeof ApiChallengesIdRouteImport
      parentRoute: typeof ApiChallengesRoute
    }
    '/etude/$surah/$ayah': {
      id: '/etude/$surah/$ayah'
      path: '/etude/$surah/$ayah'
      fullPath: '/etude/$surah/$ayah'
      preLoaderRoute: typeof EtudeSurahAyahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/lire/$surah': {
      id: '/quran/lire/$surah'
      path: '/quran/lire/$surah'
      fullPath: '/quran/lire/$surah'
      preLoaderRoute: typeof QuranLireSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/page/$page': {
      id: '/quran/page/$page'
      path: '/quran/page/$page'
      fullPath: '/quran/page/$page'
      preLoaderRoute: typeof QuranPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/$id/join': {
      id: '/api/challenges/$id/join'
      path: '/join'
      fullPath: '/api/challenges/$id/join'
      preLoaderRoute: typeof ApiChallengesIdJoinRouteImport
      parentRoute: typeof ApiChallengesIdRoute
    }
    '/api/challenges/$id/progress': {
      id: '/api/challenges/$id/progress'
      path: '/progress'
      fullPath: '/api/challenges/$id/progress'
      preLoaderRoute: typeof ApiChallengesIdProgressRouteImport
      parentRoute: typeof ApiChallengesIdRoute
    }
  }
}

interface ParametresRouteChildren {
  ParametresApparenceRoute: typeof ParametresApparenceRoute
}

const ParametresRouteChildren: ParametresRouteChildren = {
  ParametresApparenceRoute: ParametresApparenceRoute,
}

const ParametresRouteWithChildren = ParametresRoute._addFileChildren(
  ParametresRouteChildren,
)

interface ApiChallengesIdRouteChildren {
  ApiChallengesIdJoinRoute: typeof ApiChallengesIdJoinRoute
  ApiChallengesIdProgressRoute: typeof ApiChallengesIdProgressRoute
}

const ApiChallengesIdRouteChildren: ApiChallengesIdRouteChildren = {
  ApiChallengesIdJoinRoute: ApiChallengesIdJoinRoute,
  ApiChallengesIdProgressRoute: ApiChallengesIdProgressRoute,
}

const ApiChallengesIdRouteWithChildren = ApiChallengesIdRoute._addFileChildren(
  ApiChallengesIdRouteChildren,
)

interface ApiChallengesRouteChildren {
  ApiChallengesIdRoute: typeof ApiChallengesIdRouteWithChildren
}

const ApiChallengesRouteChildren: ApiChallengesRouteChildren = {
  ApiChallengesIdRoute: ApiChallengesIdRouteWithChildren,
}

const ApiChallengesRouteWithChildren = ApiChallengesRoute._addFileChildren(
  ApiChallengesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresPriereRoute: ApresPriereRoute,
  CoucherRoute: CoucherRoute,
  EcouteRoute: EcouteRoute,
  FavorisRoute: FavorisRoute,
  FavorisLectureRoute: FavorisLectureRoute,
  HorairesRoute: HorairesRoute,
  InstallRoute: InstallRoute,
  KhatmaRoute: KhatmaRoute,
  MatinRoute: MatinRoute,
  ParametresRoute: ParametresRouteWithChildren,
  RappelsRoute: RappelsRoute,
  RechercheRoute: RechercheRoute,
  ReveilRoute: ReveilRoute,
  SoirRoute: SoirRoute,
  SortieRoute: SortieRoute,
  TadabburRoute: TadabburRoute,
  VoyageRoute: VoyageRoute,
  WirdRoute: WirdRoute,
  ApiChallengesRoute: ApiChallengesRouteWithChildren,
  ChallengeIdRoute: ChallengeIdRoute,
  CompteurDhikrIdRoute: CompteurDhikrIdRoute,
  DefisNouveauRoute: DefisNouveauRoute,
  SourateSurahRoute: SourateSurahRoute,
  CompteurIndexRoute: CompteurIndexRoute,
  DefisIndexRoute: DefisIndexRoute,
  EtudeSurahAyahRoute: EtudeSurahAyahRoute,
  QuranLireSurahRoute: QuranLireSurahRoute,
  QuranPagePageRoute: QuranPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
