/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcouteRouteImport } from './routes/ecoute'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as FavorisLectureRouteImport } from './routes/favoris-lecture'
import { Route as MatinRouteImport } from './routes/matin'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SoirRouteImport } from './routes/soir'
import { Route as TadabburRouteImport } from './routes/tadabbur'
import { Route as SourateSurahRouteImport } from './routes/sourate.$surah'
import { Route as EtudeSurahAyahRouteImport } from './routes/etude.$surah.$ayah'
import { Route as QuranPagePageRouteImport } from './routes/quran.page.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcouteRoute = EcouteRouteImport.update({
  id: '/ecoute',
  path: '/ecoute',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisLectureRoute = FavorisLectureRouteImport.update({
  id: '/favoris-lecture',
  path: '/favoris-lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const MatinRoute = MatinRouteImport.update({
  id: '/matin',
  path: '/matin',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SoirRoute = SoirRouteImport.update({
  id: '/soir',
  path: '/soir',
  getParentRoute: () => rootRouteImport,
} as any)
const TadabburRoute = TadabburRouteImport.update({
  id: '/tadabbur',
  path: '/tadabbur',
  getParentRoute: () => rootRouteImport,
} as any)
const SourateSurahRoute = SourateSurahRouteImport.update({
  id: '/sourate/$surah',
  path: '/sourate/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudeSurahAyahRoute = EtudeSurahAyahRouteImport.update({
  id: '/etude/$surah/$ayah',
  path: '/etude/$surah/$ayah',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranPagePageRoute = QuranPagePageRouteImport.update({
  id: '/quran/page/$page',
  path: '/quran/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/matin': typeof MatinRoute
  '/recherche': typeof RechercheRoute
  '/soir': typeof SoirRoute
  '/tadabbur': typeof TadabburRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/matin': typeof MatinRoute
  '/recherche': typeof RechercheRoute
  '/soir': typeof SoirRoute
  '/tadabbur': typeof TadabburRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecoute': typeof EcouteRoute
  '/favoris': typeof FavorisRoute
  '/favoris-lecture': typeof FavorisLectureRoute
  '/matin': typeof MatinRoute
  '/recherche': typeof RechercheRoute
  '/soir': typeof SoirRoute
  '/tadabbur': typeof TadabburRoute
  '/sourate/$surah': typeof SourateSurahRoute
  '/etude/$surah/$ayah': typeof EtudeSurahAyahRoute
  '/quran/page/$page': typeof QuranPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/matin'
    | '/recherche'
    | '/soir'
    | '/tadabbur'
    | '/sourate/$surah'
    | '/etude/$surah/$ayah'
    | '/quran/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/matin'
    | '/recherche'
    | '/soir'
    | '/tadabbur'
    | '/sourate/$surah'
    | '/etude/$surah/$ayah'
    | '/quran/page/$page'
  id:
    | '__root__'
    | '/'
    | '/ecoute'
    | '/favoris'
    | '/favoris-lecture'
    | '/matin'
    | '/recherche'
    | '/soir'
    | '/tadabbur'
    | '/sourate/$surah'
    | '/etude/$surah/$ayah'
    | '/quran/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcouteRoute: typeof EcouteRoute
  FavorisRoute: typeof FavorisRoute
  FavorisLectureRoute: typeof FavorisLectureRoute
  MatinRoute: typeof MatinRoute
  RechercheRoute: typeof RechercheRoute
  SoirRoute: typeof SoirRoute
  TadabburRoute: typeof TadabburRoute
  SourateSurahRoute: typeof SourateSurahRoute
  EtudeSurahAyahRoute: typeof EtudeSurahAyahRoute
  QuranPagePageRoute: typeof QuranPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoute': {
      id: '/ecoute'
      path: '/ecoute'
      fullPath: '/ecoute'
      preLoaderRoute: typeof EcouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris-lecture': {
      id: '/favoris-lecture'
      path: '/favoris-lecture'
      fullPath: '/favoris-lecture'
      preLoaderRoute: typeof FavorisLectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matin': {
      id: '/matin'
      path: '/matin'
      fullPath: '/matin'
      preLoaderRoute: typeof MatinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soir': {
      id: '/soir'
      path: '/soir'
      fullPath: '/soir'
      preLoaderRoute: typeof SoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tadabbur': {
      id: '/tadabbur'
      path: '/tadabbur'
      fullPath: '/tadabbur'
      preLoaderRoute: typeof TadabburRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourate/$surah': {
      id: '/sourate/$surah'
      path: '/sourate/$surah'
      fullPath: '/sourate/$surah'
      preLoaderRoute: typeof SourateSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etude/$surah/$ayah': {
      id: '/etude/$surah/$ayah'
      path: '/etude/$surah/$ayah'
      fullPath: '/etude/$surah/$ayah'
      preLoaderRoute: typeof EtudeSurahAyahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/page/$page': {
      id: '/quran/page/$page'
      path: '/quran/page/$page'
      fullPath: '/quran/page/$page'
      preLoaderRoute: typeof QuranPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcouteRoute: EcouteRoute,
  FavorisRoute: FavorisRoute,
  FavorisLectureRoute: FavorisLectureRoute,
  MatinRoute: MatinRoute,
  RechercheRoute: RechercheRoute,
  SoirRoute: SoirRoute,
  TadabburRoute: TadabburRoute,
  SourateSurahRoute: SourateSurahRoute,
  EtudeSurahAyahRoute: EtudeSurahAyahRoute,
  QuranPagePageRoute: QuranPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
